### ISSUE TITLE
Replace "allophone" with "sound"

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/wiki#121]
Update Webapp:
- [x] Update webapp UI: https://github.com/elimu-ai/webapp/issues/1497
- [x] Update model library: https://github.com/elimu-ai/model/issues/255
- [x] Update webapp backend code: https://github.com/elimu-ai/webapp/issues/1497
- [x] Update REST API endpoints
- [ ] Update Wiki documentation

---

Update Android apps using the Webapp's REST API:
- [x] Content Provider: https://github.com/elimu-ai/content-provider/issues/86
- [x] Crowdsource: https://github.com/elimu-ai/crowdsource/issues/34
